### ISSUE TITLE
Retornar Feature em com `F` em uppercase

### ISSUE THREAD

**Issue by renatocron** [h-pgy/sepep_geoloc#1]
Bom dia, @h-pgy 
você consegue alterar para esse 
https://github.com/h-pgy/sepep_geoloc/blob/3ef69c8052fb0352ed9198bf67d0181e7fd9a857/api/core/schemas/geojson.py#L19
 voltar com o F em uppercase? Eu tentei alterar na minha versão, mas tem algum lugar do código mudando para lower-case ou algo assim.

A minha lib de validação do GeoJSON não está aceitando com o f em lowercase

**Comment by h-pgy** [comment]
Opa faço já.

**Comment by h-pgy** [comment]
Done. Desculpa a demora, pintaram umas reuniões aqui. Checa se está tudo certo please e eu já fecho.

**Comment by renatocron** [comment]
@h-pgy agora voltou certinho!

Agora é só a questão do EPSG:31983 que está pegando pra gente mesmo, pois tentei converter usando o postgis e ele dá um erro dizendo que o objeto está inválido, e no https://geojsonlint.com/ ele diz também uma mensagem que é por causa da ordem de algum dos vetores. Eu vou esperar você finalizar para plotar as camadas e aplicar a regra de simplifcar no SMAE.
